# --------------------( LICENSE                           )--------------------
# Copyright (c) 2014-2021 Cecil Curry.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                          )--------------------
# Project-wide Read The Docs (RTD) configuration.

# ....................{ METADATA                          }....................
# RTD configuration scheme version this file complies with.
version: 2

# ....................{ INSTALLATION                      }....................
python:
  install:
    - method: pip
      path: .

      #FIXME: Actually define a new "doc-rtd" extra in "setup.py", please. To
      #do so, let's convert the existing "doc/source/requirement.txt" file into
      #our ad-hoc project-specific format to enable developers to manually
      #mimic this exact RTD configuration. To facilitate this:
      #* Define a new "beartype.meta.LIBS_DOCTIME_MANDATORY" tuple resembling:
      #    LIBS_DOCTIME_MANDATORY = {
      #        'sphinx >=3.4.3',
      #        'sphinx-rtd-theme >=0.5.1',
      #    }
      #* Define a new 'extras_require' key-value pair in setup resembling:
      #        'doc': meta.LIBS_DOCTIME_MANDATORY,
      extra_requirements:
        - doc-rtd

  system_packages: true

# ....................{ SPHINX                            }....................
sphinx:
  # For safety, convert non-fatal Sphinx warnings into fatal errors.
  fail_on_warning: true
